### ISSUE TITLE
Drizzle reports memory heap error when converting MOUL(a) to Drizzle

### ISSUE THREAD

**Issue by RowanSkie** [Jrius/Drizzle#2]
There are four files that cause Drizzle to get an OutOfMemoryError, and it happens during conversion itself from MOULa to Drizzle. Is there a way to fix this?

```
Conversion of files...
Conversion of Neighborhood02_District_krelKirel.prp
Error: Exception in thread: "AWT-EventQueue-0"
java.lang.OutOfMemoryError: Java heap space

   at java.base/java.lang.reflect.Array.newArray(Native Method)

   at java.base/java.lang.reflect.Array.newInstance(Unknown Source)

   at uru.context.readArray(context.java:165)

   at prpobjects.plHKPhysical$PXMeshBounds.<init>(plHKPhysical.java:1703)

   at prpobjects.plHKPhysical$PXPhysical.<init>(plHKPhysical.java:763)

   at prpobjects.plHKPhysical.<init>(plHKPhysical.java:579)

   at prpobjects.PrpObject.getObject(PrpObject.java:83)

   at prpobjects.PrpObject.<init>(PrpObject.java:444)

   at prpobjects.PrpRootObject.<init>(PrpRootObject.java:68)

   at prpobjects.prputils.ProcessAllMoul(prputils.java:324)

   at prpobjects.prpfile.createFromContext(prpfile.java:324)

   at auto.conversion.convertPrp(conversion.java:178)

   at auto.conversion.convertFile(conversion.java:119)

   at auto.AllGames$GameConversionSub.ConvertFiles(AllGames.java:310)

   at gui.Gui.jButton66ActionPerformed(Gui.java:6354)

   at gui.Gui.access$18000(Gui.java:45)

   at gui.Gui$182.actionPerformed(Gui.java:4795)

   at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

   at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

   at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)

   at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)

   at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)

   at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)

   at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)

   at java.desktop/java.awt.Component.processEvent(Unknown Source)

   at java.desktop/java.awt.Container.processEvent(Unknown Source)

   at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)

   at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)

   at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)

   at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

   at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)

   at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)

--
((Trying again with a different file))

Conversion of files...
Conversion of Personal_District_psnlMYSTII.prp
Error: Exception in thread: "AWT-EventQueue-0"
java.lang.OutOfMemoryError: Java heap space

--
((Trying again with a different file))

Conversion of files...
Conversion of GreatTreePub_District_GreatTree.prp
Error: Exception in thread: "AWT-EventQueue-0"
java.lang.OutOfMemoryError: Java heap space

--
((Trying again with a different file)(

Conversion of files...
Conversion of GreatTreePub_District_Pub.prp
Error: Exception in thread: "AWT-EventQueue-0"
java.lang.OutOfMemoryError: Java heap space

---
```

**Comment by Jrius** [comment]
Thanks for the report, should be fixed. [Head to the forums to download the new version](https://forum.guildofwriters.org/viewtopic.php?f=114&t=6688). Sorry it took so long ;)
